In [ ]:
l2 = [
    [1, 2, 3],
    [4, 5, 6]
]
l2

[[1, 2, 3], [4, 5, 6]]

In [ ]:
l1 = [1, 2, 3, 4]
[i + 2 for i in l1]

[3, 4, 5, 6]

NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

In [ ]:
# array

!pip install numpy

In [ ]:
import numpy as np
np.array(l2)
type(np.array(l2))

numpy.ndarray

In [ ]:
a2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a3d = np.array([
    [
        [1, 2], [3, 4]
    ],
    [
        [5, 6], [7, 8]
    ]
])

a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
a3d.dtype

dtype('int64')

In [ ]:
a = np.array([1, 2, 3, 4, 5, 256], dtype=np.uint64) # unsigned integer
a

array([  1,   2,   3,   4,   5, 256], dtype=uint64)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 256], dtype=np.uint8) # unsigned integer
a

OverflowError: Python integer 256 out of bounds for uint8

In [ ]:
np.arange(10,15,2)

array([10, 12, 14])

In [ ]:
np.linspace(10, 15, 2)

array([10., 15.])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
ones=np.ones((2,3))

In [ ]:
# np.sevens(2)
ones*7

array([[7., 7., 7.],
       [7., 7., 7.]])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])