In [2]:
import numpy as np
# 1
vect = np.arange(10, 50)
print("1. Vector from 10 to 49:\n", vect)

1. Vector from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 2
vect_matr = np.arange(0, 9).reshape(3,3)
print("3x3\n", vect_matr)

3x3
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 3
# vect_ident = np.identity(3)
# print("3x3\n", vect_ident)

vect_ident = np.eye(3)
print("3x3\n", vect_ident)

3x3
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 4
vect_3x3x3 = np.random.random((3,3,3))
print("3x3x3\n", vect_3x3x3)

3x3x3
 [[[0.19527294 0.69644237 0.79530971]
  [0.4199259  0.38074743 0.65542747]
  [0.35061329 0.55259584 0.8387137 ]]

 [[0.51590785 0.65448165 0.74521398]
  [0.69575348 0.51939879 0.35657834]
  [0.79426116 0.70942152 0.39504311]]

 [[0.87035791 0.39618512 0.54344752]
  [0.96510038 0.11773476 0.73013819]
  [0.07777012 0.8057694  0.84351035]]]


In [ ]:
# 5

vect_10x10 = np.random.random((10,10))
max= vect_10x10.max()
min= vect_10x10.min()
print("Max: ", max)
print("Min: ", min)
print("10x10\n", vect_10x10)

Max:  0.9715619038278492
Min:  0.00884676847420618
10x10
 [[0.52185802 0.32726366 0.54342612 0.90427919 0.37706593 0.61883616
  0.15014082 0.39773029 0.66513146 0.18959807]
 [0.36637858 0.65563984 0.71349897 0.81155642 0.1101914  0.49796269
  0.22492844 0.05853261 0.32949153 0.77056736]
 [0.71640902 0.24547469 0.85452482 0.2234546  0.69766114 0.86801621
  0.90239923 0.11682112 0.5455243  0.11165713]
 [0.28271422 0.32067719 0.66739193 0.02788686 0.75507798 0.9068252
  0.40670084 0.78853873 0.22455062 0.17421921]
 [0.68340564 0.23883224 0.2627769  0.48419729 0.20648909 0.19368224
  0.3973726  0.7418619  0.95651312 0.70560248]
 [0.02307307 0.30335876 0.00884677 0.18012368 0.19522486 0.17851653
  0.02114893 0.53534605 0.1319343  0.64609172]
 [0.20195584 0.71225007 0.62512468 0.89989707 0.03349004 0.45527765
  0.42273874 0.33433771 0.40820863 0.02017573]
 [0.2315684  0.64583487 0.77683457 0.15500967 0.76605461 0.74704358
  0.73995045 0.37474377 0.0297522  0.5670148 ]
 [0.79097124 0.21478533

In [ ]:
# 6

vect_10= np.random.random(10)
print(vect_10)
# mean=vect_10.mean(vect_10.sort())
mean=np.mean(np.sort(vect_10))
print("Mean 10\n", mean)
#

[0.66619915 0.55385898 0.22671895 0.62469757 0.07317729 0.38906999
 0.81015521 0.80147915 0.35967801 0.49967397]
Mean 10
 0.5004708271089194


In [ ]:
# 7
vect_5x5=np.random.random((5,5))
normalized_matrix = (vect_5x5 - np.min(vect_5x5)) / (np.max(vect_5x5) - np.min(vect_5x5))
print("\n7. Normalized 5x5 matrix:\n", normalized_matrix)


7. Normalized 5x5 matrix:
 [[0.12550584 0.7236577  0.01600812 0.54489998 0.48375817]
 [0.         0.30231343 0.95259643 0.58452726 0.94707468]
 [0.80466276 0.3101128  0.17288371 0.10572956 0.9836474 ]
 [0.59723394 0.25567564 0.82088865 0.14992893 0.00959227]
 [0.62175694 1.         0.00855381 0.86771511 0.32341954]]


In [ ]:
# 8

matr_5x3=np.random.random((5,3))
matr_3x2=np.random.random((3,2))
result=np.dot(matr_5x3, matr_3x2)
print('Matrix Product 5x3 and 3x2 is \n',result)

Matrix Product 5x3 and 3x2 is 
 [[0.665727   0.41585546]
 [0.49913807 0.45106744]
 [1.12732358 0.9451171 ]
 [0.62112334 0.42174127]
 [0.93661282 0.9373832 ]]


In [3]:
# 9

matr_3x3_1=np.random.random((3,3))
matr_3x3_2=np.random.random((3,3))
result=np.dot(matr_3x3_1, matr_3x3_2)
print('Matrix Product 3x3 and 3x3 is \n',result)
#

Matrix Product 3x3 and 3x3 is 
 [[0.71408757 0.89171976 0.81873919]
 [0.55233026 0.9015601  0.88739476]
 [0.36110936 0.64532579 0.69341492]]


In [4]:
# 10

mart_4x4=np.random.random((4,4))
transpose=mart_4x4.T
print('Transpose 4x4 matrix is \n',transpose)

Transpose 4x4 matrix is 
 [[0.55781931 0.84038041 0.55004747 0.25489872]
 [0.80817949 0.30511264 0.26960022 0.54702142]
 [0.95118883 0.32717152 0.52327581 0.41808589]
 [0.4610426  0.47503025 0.17116553 0.29360791]]


In [5]:
# 11
matr_3x3=np.random.random((3,3))
determinant=np.linalg.det(matr_3x3)
print('Determinant 3x3 matrix is \n',determinant)

Determinant 3x3 matrix is 
 0.06496161050186595


In [6]:
# 12

A_matr=np.random.random((3,4))
B_matr=np.random.random((4,3))
product_AB = np.dot(A_matr, B_matr)
print("\n12. Matrix product A (3x4) · B (4x3):\n", product_AB)



12. Matrix product A (3x4) · B (4x3):
 [[1.35116315 0.83081931 1.64079615]
 [0.63351692 0.29722696 0.93731039]
 [0.36257056 0.2006659  0.48764393]]


In [7]:
# 13

matrix_3x3_mv = np.random.random((3, 3))
vector_3x1 = np.random.random((3, 1))
mv_product = np.dot(matrix_3x3_mv, vector_3x1)
print("\n13. Matrix-vector product:\n", mv_product)


13. Matrix-vector product:
 [[0.50765423]
 [0.53009502]
 [0.05703256]]


In [8]:
A = np.random.random((3, 3))
b = np.random.random((3, 1))
x = np.linalg.solve(A, b)
print("\n14. Solution to Ax = b:\n", x)


14. Solution to Ax = b:
 [[ 0.37517165]
 [ 2.27427922]
 [-2.70447201]]


In [9]:
matrix_5x5_sums = np.random.random((5, 5))
row_sums = np.sum(matrix_5x5_sums, axis=1)
col_sums = np.sum(matrix_5x5_sums, axis=0)
print("\n15. Row-wise sums:", row_sums)
print("Column-wise sums:", col_sums)


15. Row-wise sums: [2.03361102 3.43572678 2.76631108 1.88518996 2.63913634]
Column-wise sums: [1.63735637 2.02097442 3.88394777 3.41978385 1.79791276]
